# name: 自动同步
# on:
#     push:
#         branches: [main]

# jobs:
#     sync:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout
#               uses: actions/checkout@v4
